### ISSUE TITLE
how to enable regular expressions for digital?

### ISSUE THREAD

**Issue by nixuewei** [rainydew/jsoncomparedeep#1]
`{
  "requestID": "^(.*)$",
  "signature": {
      "*": "*"
  },
  "results": [
      {
          "myBucket": {
              "country": "China",
              "friends": {
                  "female": "Lily",
                  "male": "Terry"
              },
              "name": "Tim"
          }
      }
  ],
  "status": "success",
  "metrics": {
      "elapsedTime": "^(.*)$",
      "executionTime": "^(.*)$",
      "resultCount": 1,
      "resultSize": 88
  }
}`

how to write regular expressions for "resultCount": 1
i write "resultCount": ^(.*)$ it does not work

**Comment by rainydew** [comment]
Hi there~ You can use argument **ignore_path** to ignore values of **any type**. E.g.
```python3
from json_compare import Jcompare
cp = Jcompare()
a = {"key1": 123, "key2": 456}
b = {"key1": 456, "key2": 456}
print(cp.compare(a, b, ignore_path=["/key1"]))
```
Will be
```
a is {'key2': 456, 'key1': 123}
b is {'key2': 456, 'key1': 456}
ignore_list_seq = True, re_compare = True, ignore_path = ['/key1'], float_fuzzy_digits = 0
True
Process finished with exit code 0
```

This *path* supports any regular expression that starts with ^ or ends with $. Then you can ignore sets of paths.
This feature is useful when asserting database results, or just ignoring items of an in-list dictionary.

```python3
from json_compare import Jcompare
cp = Jcompare()
a = {"res": [{"key1": 123, "key2": 456}, {"key1": 789, "key2": 456}]}
b = {"res": [{"key1": 654, "key2": 456}, {"key1": 654, "key2": 456}]}
print(cp.compare(a, b, ignore_path=["^(/res/\d+/key1)$"]))
```
It means we need to ignore any dictionary value of *key1* KEY, which dict is an element of the list with path */res*
As the above example, we will get
```
a is {'res': [{'key2': 456, 'key1': 123}, {'key2': 456, 'key1': 789}]}
b is {'res': [{'key2': 456, 'key1': 654}, {'key2': 456, 'key1': 654}]}
ignore_list_seq = True, re_compare = True, ignore_path = ['^(/res/\\d+/key1)], float_fuzzy_digits = 0
True
Process finished with exit code 0
```

As the case you mentioned
Just add */resultCount* to **ignore_path**

```python3
assert cp.compare(a, b, ignore_path=["/resultCount"])
```

**Comment by nixuewei** [comment]
Thank you Rainy.  It works now base on your suggestion!
